'''
    This file provides an example for the use of the shipp package.
    The objective is to size a single storage to satisfy a baseload power production considering an arbitrary power production and price time series.
'''

import numpy as np
import numpy_financial as npf
import matplotlib.pyplot as plt


from shipp.kernel_pyomo import solve_lp_pyomo
from shipp.components import Storage, Production, TimeSeries
from shipp.kernel import solve_lp_sparse

# Global input data for the numerical experiments
n = 20 * 24  # number of time steps 
dt = 1 # time step duration [hour]
percent_bl = 0.99 # reliability of the baseload constraint
discount_rate = 0.03 # discount rate
n_year = 20  # Project duration [years]
p_min = 10 # Required minimum baseload power
p_cost_res = 3000  # USD/MW # cost per installed capacity of the renewable energy source [USD/MW]

# Input data for the storage characteristics
p_cost = 150*1e3  # cost per power capacity for the short term storage [USD/MW]
e_cost = 75 * 1e3 # cost per energy capacity for the short term storage [USD/MWh]
eta = 0.85 #Round trip efficiency for the short term storage

pyo_solver = 'none' # Name of the optimization solver (e.g. cplex, gurobi, mosek) - if 'none', default to linprog

# Input parameters to generate a dummy power and price signals
frequency_power = 0.5 
frequency_price = 5
mean_power = 50
price_low = 40
price_high = 60
p_max = 100

time = np.arange(0, n)/24

# The power is represented by a sine function of time
power = mean_power*(1.0+np.sin(time * 2*np.pi * frequency_power))

# The price is represented by the combinaison of a sine function of time and a random variation
price = np.random.uniform(price_low, price_high, n) + \
        10*np.sin(np.arange(0, n)/24 * 2*np.pi * frequency_price)


# Building objects representing the storage system
stor = Storage(e_cap = None, p_cap = None, eff_in = 1, eff_out= eta, e_cost = e_cost, p_cost = p_cost)
stor_null = Storage(e_cap = 0, p_cap = 0, eff_in =1, eff_out=1,  e_cost = 0, p_cost = 0) # Creation of a null object - necessary for the optimization function

price_dam = TimeSeries(price, dt)

# Building objects representing the power production assets
power_ts = TimeSeries(power, dt)
prod = Production(power_ts, p_cost_res)
prod_null = Production(TimeSeries([0 for _ in range(n)], dt), 0) # Creation of a null object - necessary for the optimization function


if pyo_solver == 'none':
    if n>150*24: 
        n = 150*24
        print('Number of time steps limited to 3600 due to the poor performance of solver linprog on large problems.')
    
    # Solve the problem where the matrices are built directly for use in linprog
    os =  solve_lp_sparse(price_dam, prod, prod_null, stor, stor_null, discount_rate, n_year, p_min, p_max, n)
else:
    # Solve the problem with pyomo, where the problem is build implicitely from description of the constraints, objective function and design variables
    os =  solve_lp_pyomo(price_dam, prod, prod_null, stor, stor_null, discount_rate, n_year, p_min, p_max, n, pyo_solver)


revenues_res_only = np.dot(price, np.minimum(power, p_max))*dt  # Part of revenues generated by the renewable energy source only
revenue_storage = os.revenue_storage # Part of revenues generated by the storage only
a_npv = os.get_added_npv(discount_rate, n_year)  # "Added" NPV, meaning the difference of NPV due to the addition of a storage system

print('P_min [MW]\tRevenue [kUSD]\tRev. increase\tp_cap1/e_cap1\t\
      p_cap2/e_cap2\tCost BL [M.USD]\tTot NPV [M.USD]')
print('{:.1f}\t\t{:.1f}\t\t{:.2f}%\t\t{:.2f}/{:.2f}\t\t{:.2f}/{:.2f}\
      \t{:.2f}\t\t{:.1f}'.format(p_min, os.revenue*1e-3, 
                                 100*(os.revenue/revenues_res_only-1),
                                 os.storage_list[0].p_cap, 
                                 os.storage_list[0].e_cap, 
                                 os.storage_list[1].p_cap, 
                                 os.storage_list[1].e_cap, -a_npv, os.npv))
                                 